### ISSUE TITLE
FE Homepage

### ISSUE THREAD

**Issue by reneepinna** [Refugee-Aid-Capstone/refugee_aid_be#9]
A user can visit the homepage with a navbar, hero image
The homepage will have the mission statement
a video and a call to action

**Comment by Sulton88Mehron90** [comment]
Design and develop a homepage that should include the following features:

Navbar: A navigation bar at the top of the homepage. Further details on the links and functionalities to be included in the navbar are required.
Hero Image: A prominent image at the top section of the homepage. Need specifics on the image content and any overlaying text or callouts.
Mission Statement: Clearly display the mission statement of the organization/site. The actual text for the mission statement is required.
Video: Embed a video related to the organization/site. Details of the video content and source are needed.
Call to Action: Implement a call-to-action (CTA) section/button that prompts users to take some action. Specifics on what action we are prompting users to take (e.g., sign up, learn more, donate, etc.) and the design of the CTA are required.
Acceptance Criteria:

The homepage should be responsive and look consistent across different devices and screen sizes.
All elements should be clearly visible and accessible.
The video should play smoothly and be embedded properly without breaking the layout.
The call to action should be prominent and intuitive for users.
